workflows:
  flutter-ci:
    name: Flutter CI/CD Pipeline
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Analyze code
        script: |
          flutter analyze

      - name: Run tests
        script: |
          flutter test

      - name: Build APK
        script: |
          flutter build apk --release --build-number=1

      # - name: Build iOS
      #   script: |
      #     flutter build ipa --release --build-number=1

    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa

